'use strict';
const width = 5;
const height = 7;
const area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
const bill = 5;
const payment = 10;
const change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
const quizzes = 15;
const midterm = 45;
const final = 30;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Shea';
const lastName = 'Pone';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 8;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount = 270;
const isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
let motto = fullName;
motto += ' is the Goat';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
